server:
  port: 8080
  #加入/demo前缀
  context-path: /api

#DataSource
#数据库驱动
jdbc:
  driver: com.mysql.jdbc.Driver
  #数据库链接
  url: jdbc:mysql://localhost:3306/xdhc304?useUnicode=true&characterEncoding=utf8&useSSL=false
  #数据库用户名
  username: root
  #数据库密码
  password: root

#Mybatis
mybatis_config_file: mybatis-config.xml
mapper_path: /mapper/**.xml
type_alias_package: com.imooc.demo.entity

spring:
  cache:
    type: redis
  mail:
    host: smtp.163.com
    username: 1*156*156*6@163.com
    password: abcd1234
    port: 25
    protocol: smtp
    default-encoding: UTF-8
#    properties:
#      mail:
#        smtp:
#          auth: true
#          ssl:
#            enable: true
  #是否用启用加密传送的协议验证项
  #注意：在spring.mail.password处的值是需要在邮箱设置里面生成的授权码，这个不是真实的密码。

redis:
  database: 0
  host: 127.0.0.1
  port: 6379
#  password: 1234
#  pool:
#    max-active: 100
#    max-wait: -1
#    max-idle: 10
#    min-idle: 0
  timeout: 3

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql